name: Deploy to Yandex Cloud Functions

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
  SA_ID: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy Function
        uses: yc-actions/yc-sls-function@v4
        with:
          yc-sa-id: ${{ env.SA_ID }}
          folder-id: ${{ env.FOLDER_ID }}
          function-name: telegram-bot
          runtime: python312
          entrypoint: index.handler
          memory: 128Mb
          source-root: .
          include: |
            src/**
            requirements.txt
          environment: |
            TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
            WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}